### ISSUE TITLE
Initialize the Frontend

### ISSUE THREAD

**Issue by AhmedFatthy1040** [AhmedFatthy1040/hias#10]
Set up the React.js frontend in the `app` folder using TypeScript. Install essential libraries and define a modular folder structure.  

- **Tasks**:  
  - [ ] Navigate to the `app` folder and create a React project:
    ```bash
    cd app
    npx create-react-app . --template typescript
    ```
  - [ ] Install required libraries:
    - **React Router** for navigation:
      ```bash
      npm install react-router-dom
      ```
    - **Tailwind CSS** for styling:
      ```bash
      npm install -D tailwindcss postcss autoprefixer
      npx tailwindcss init
      ```
  - [ ] Create the following folder structure:
    ```
    app/src/
    ├── components/       # Reusable components
    ├── pages/            # Page-level components
    ├── services/         # API calls
    ├── App.tsx           # Main app component
    └── index.tsx         # React entry point
    ```
  - [ ] Verify the frontend runs without errors.

**Comment by justFadel19** [comment]
.
