### ISSUE TITLE
Create Wireframes for the Annotation Editor

### ISSUE THREAD

**Issue by AhmedFatthy1040** [AhmedFatthy1040/hias#2]
Design the wireframes for the annotation editor using **Figma** or **Adobe XD**. Include:  
  - A canvas for drawing polygons.  
  - A dropdown or input field for label assignment.  
  - Undo/Redo buttons for user actions.  

- **Tasks**:  
  - [ ] Canvas design for polygon drawing.  
  - [ ] Add label assignment field.  
  - [ ] Include Undo/Redo buttons.

**Comment by justFadel19** [comment]
Assign it to me.
