### ISSUE TITLE
Create Wireframes for the Dashboard

### ISSUE THREAD

**Issue by AhmedFatthy1040** [AhmedFatthy1040/hias#3]
Design the dashboard wireframes to manage uploaded images and display progress. Include:  
  - Image upload form with category selection.  
  - Categorized image grid or list view.  
  - Progress tracker showing the number of annotated vs. total images.  

- **Tasks**:  
  - [ ] Design image upload form.  
  - [ ] Create grid or list view for categorized images.  
  - [ ] Add a progress tracker component.

**Comment by justFadel19** [comment]
Assign it to me.
