### ISSUE TITLE
Define API Specifications for User Management

### ISSUE THREAD

**Issue by AhmedFatthy1040** [AhmedFatthy1040/hias#5]
Define API specifications for user authentication and management using **Swagger/OpenAPI** or **Postman**. Include:  
  - `POST /auth/signup`: Register new users.  
  - `POST /auth/login`: Authenticate users and return JWT.  

- **Tasks**:  
  - [ ] Define request/response structures for `POST /auth/signup`.  
  - [ ] Define request/response structures for `POST /auth/login`.  
  - [ ] Validate API design with team feedback.

**Comment by ShrouqSalem** [comment]
Assign it to me
